prompts = [
    "A close-up of the intricate patterns on a butterfly's wings.",
    "An ancient tree with sprawling branches and dense foliage.",
    "The complex gears inside a vintage pocket watch.",
    "A cobblestone street winding through a medieval village.",
    "The shimmering scales of a fish under sunlight.",
    "A field of wheat swaying gently in the wind.",
    "An owl's feathers ruffled by a soft breeze.",
    "A spider's web glistening with morning dew.",
    "The detailed embroidery on a traditional garment.",
    "An aerial view of terraced rice fields on a hillside.",
    "The network of veins in a leaf held up to the light.",
    "A cat's whiskers twitching as it senses movement.",
    "A bee collecting pollen from a vibrant sunflower.",
    "The pattern of bricks in an old castle wall.",
    "The weathered hands of an elderly person holding a flower.",
    "The distinctive fur patterns on a wild leopard.",
    "A bustling marketplace filled with colorful fabrics and spices.",
    "The interwoven threads of an intricate tapestry.",
    "Water droplets clinging to a spider's web after rain.",
    "An ant carrying a leaf many times its size.",
    "The textured bark of an ancient oak tree.",
    "A flock of birds forming patterns against the sky.",
    "Cream swirling into a freshly brewed cup of coffee.",
    "The elaborate carvings on a temple door.",
    "The overlapping petals of a blooming rose.",
    "A mountain range showing layers of sedimentary rock.",
    "A peacock displaying its vibrant tail feathers.",
    "A city skyline reflected in the calm water at night.",
    "Ice crystals forming patterns on a windowpane.",
    "A crowd of people crossing a busy urban street.",
    "The intricate circuitry on a computer microchip.",
    "A snake coiled in the grass, showcasing its scales.",
    "A jellyfish floating gracefully in the ocean depths.",
    "The intertwined roots of mangrove trees in a swamp.",
    "A mosaic made from thousands of colorful tiles.",
    "Visible brushstrokes on a large oil painting.",
    "A colony of penguins huddled together on ice.",
    "The fine grains of sand forming ripples on a beach.",
    "A horse's mane flowing as it gallops.",
    "A honeycomb filled with golden honey.",
    "The facade of a building adorned with ornate balconies.",
    "The veins visible on the back of a person's hand.",
    "A school of fish swimming in perfect unison.",
    "The overlapping scales on a pinecone.",
    "A violinist's fingers moving swiftly on the strings.",
    "An old map with detailed compass roses and sea monsters.",
    "An eagle's sharp eye scanning the landscape below.",
    "The swirling patterns of a distant galaxy in space.",
    "A library filled with rows of ancient books.",
    "The layered petals of a lotus flower in a pond.",
    "A market stall overflowing with fresh fruits and vegetables.",
    "The unique patterns of a snowflake under a microscope.",
    "A snail's shell showcasing a perfect spiral.",
    "The tangled wires and cables on a utility pole.",
    "An old barn constructed with weathered wooden planks.",
    "A firefighter's uniform covered in ash and soot.",
    "The marbled veins running through a piece of granite.",
    "An aerial view of a city's intricate street grid.",
    "The delicate threads of silk spun by a caterpillar.",
    "A dancer's flowing dress captured in mid-twirl.",
    "The textured skin of an elephant in close-up.",
    "A macro shot of an eye revealing detailed iris patterns.",
    "The detailed stitches in a handcrafted quilt.",
    "A vast field of lavender in full bloom.",
    "Ripples forming on a pond from falling raindrops.",
    "A coral reef teeming with diverse marine life.",
    "The layered feathers of a bird's wing spread wide.",
    "An architect's blueprint spread across a table.",
    "The cross-section of a tree trunk showing growth rings.",
    "A clock tower with ornate hands and Roman numerals.",
    "A horse-drawn carriage traveling on a cobblestone road.",
    "Mountains reflected perfectly in a still lake.",
    "A close-up of the weave in a piece of fabric.",
    "The swirling colors within a polished marble slab.",
    "Festival-goers dressed in an array of colorful costumes.",
    "The intricate metalwork of a wrought-iron gate.",
    "A garden maze formed by tall, manicured hedges.",
    "The cratered surface of the moon as seen through a telescope.",
    "A collection of seashells scattered along the shore.",
    "Tiny bubbles rising in a glass of champagne.",
    "A musician's hands gracefully playing the piano.",
    "The fine hairs covering a caterpillar's body.",
    "A medieval tapestry depicting a historical battle.",
    "Layered rock formations in the Grand Canyon.",
    "An anthill bustling with tiny workers.",
    "A fingerprint pressed onto a glass surface.",
    "The precise stitching on a professional baseball.",
    "A rainbow appearing over a cascading waterfall.",
    "Overlapping clay tiles on a traditional roof.",
    "An urban skyline silhouetted against a sunset.",
    "Ancient hieroglyphs carved into a stone tablet.",
    "A field of sunflowers all facing the rising sun.",
    "The colorful designs in a stained-glass window.",
    "A bird's nest carefully woven from twigs and leaves.",
    "Trees reflected upside-down in a tranquil pond.",
    "Railroad tracks converging into the distant horizon.",
    "Interlacing branches forming a canopy in a forest.",
    "An ornate chandelier adorned with sparkling crystals.",
    "A honeybee hovering over a flower's stamen.",
    "The flaky layers of a freshly baked croissant."
]